### ISSUE TITLE
Readme.md's Gitter link is broken

### ISSUE THREAD

**Issue by jgallare** [interledger-deprecated/java-spsp-client-spring#6]
It looks like this:
```
[![gitter][gitter-image]][gitter-url]
```
Removed in #5 for the moment, tried to copypaste from other projects but still wouldn't show.

**Comment by sappenin** [comment]
I think the links are just missing. Maybe have a look at how it's structured on the java-ilp-core project ([here](https://github.com/interledger/java-ilp-core)).

Specifically, looks like this is the source for gitter and various other badges:

```
[gitter-url]: https://gitter.im/interledger/java
[gitter-image]: https://badges.gitter.im/interledger/java.svg
[circle-image]: https://circleci.com/gh/interledger/java-ilp-core.svg?style=shield
[circle-url]: https://circleci.com/gh/interledger/java-ilp-core
[codecov-image]: https://codecov.io/gh/interledger/java-ilp-core/branch/master/graph/badge.svg
[codecov-url]: https://codecov.io/gh/interledger/java-ilp-core
```

**Comment by jgallare** [comment]
Fixed in the latest commit, apparently IntelliJ's .md plugin is broken and doesn't display URL images properly, I just tried pushing to my branch and it shows OK.

Issue solved!
